function handleException(errorMessage: string): never{
    throw Error(errorMessage);
}